/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
#include "COMP_SERIAL.h"
#include "TX_REPEATER_14.h"
#include "TX_REPEATER_23.h"
#include "TX_TIMEOUT.h"
#include "RECEIVE_1.h"
#include "RECEIVE_2.h"
#include "RECEIVE_3.h"
#include "RECEIVE_4.h"
#include "RX_TIMEOUT.h"
