//*****************************************************************************
//*****************************************************************************
//  FILENAME: RECEIVE_3.h
//   Version: 3.3, Updated on 2009/7/10 at 10:46:15
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION:  RX8 User Module C Language interface file for the
//                22/24/25/26/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


// include the global header file
#include <m8c.h>

#define RECEIVE_3_RXBUF_ENABLE 1

//-------------------------------------------------
// Prototypes of the RECEIVE_3 API.
//-------------------------------------------------

#if ( RECEIVE_3_RXBUF_ENABLE )
extern char RECEIVE_3_aRxBuffer[];
extern BYTE RECEIVE_3_bRxCnt;
extern BYTE RECEIVE_3_fStatus;
#endif

// Create pragmas to support proper argument and return value passing
#pragma fastcall16  RECEIVE_3_EnableInt
#pragma fastcall16  RECEIVE_3_DisableInt
#pragma fastcall16  RECEIVE_3_Start
#pragma fastcall16  RECEIVE_3_Stop
#pragma fastcall16  RECEIVE_3_bReadRxData
#pragma fastcall16  RECEIVE_3_bReadRxStatus

#pragma fastcall16  RECEIVE_3_cGetChar
#pragma fastcall16  RECEIVE_3_cReadChar
#pragma fastcall16  RECEIVE_3_iReadChar

#if ( RECEIVE_3_RXBUF_ENABLE )
#pragma fastcall16  RECEIVE_3_CmdReset
#pragma fastcall16  RECEIVE_3_bCmdCheck
#pragma fastcall16  RECEIVE_3_bErrCheck
#pragma fastcall16  RECEIVE_3_bCmdLength
#pragma fastcall16  RECEIVE_3_szGetParam
#pragma fastcall16  RECEIVE_3_szGetRestOfParams
#endif

//-------------------------------------------------
// Prototypes of the RECEIVE_3 API.
//-------------------------------------------------
extern void  RECEIVE_3_EnableInt(void);
extern void  RECEIVE_3_DisableInt(void);
extern void  RECEIVE_3_Start(BYTE bParity);
extern void  RECEIVE_3_Stop(void);
extern BYTE  RECEIVE_3_bReadRxData(void);
extern BYTE  RECEIVE_3_bReadRxStatus(void);

// High level RX functions
extern CHAR         RECEIVE_3_cGetChar(void);
extern CHAR         RECEIVE_3_cReadChar(void);
extern INT          RECEIVE_3_iReadChar(void);

#if ( RECEIVE_3_RXBUF_ENABLE )
extern void   RECEIVE_3_CmdReset(void);
extern BYTE   RECEIVE_3_bCmdCheck(void);
extern BYTE   RECEIVE_3_bErrCheck(void);
extern BYTE   RECEIVE_3_bCmdLength(void);
extern char * RECEIVE_3_szGetParam(void);
extern char * RECEIVE_3_szGetRestOfParams(void);
#endif

// Old function call names, do not use.
// These names will be removed in a future release.
#pragma fastcall16 bRECEIVE_3_ReadRxData
#pragma fastcall16 bRECEIVE_3_ReadRxStatus
extern BYTE bRECEIVE_3_ReadRxData(void);
extern BYTE bRECEIVE_3_ReadRxStatus(void);

//-------------------------------------------------
// Constants for RECEIVE_3 API's.
//-------------------------------------------------

//------------------------------------
// Receiver Interrupt masks
//------------------------------------
#define RECEIVE_3_INT_REG_ADDR                 ( 0x0e1 )
#define RECEIVE_3_bINT_MASK                    ( 0x40 )

//------------------------------------
// Receiver Parity masks
//------------------------------------
#define  RECEIVE_3_PARITY_NONE         0x00
#define  RECEIVE_3_PARITY_EVEN         0x02
#define  RECEIVE_3_PARITY_ODD          0x06

//------------------------------------
//  Receiver Status Register masks
//------------------------------------
#define  RECEIVE_3_RX_ACTIVE           0x10
#define  RECEIVE_3_RX_COMPLETE         0x08
#define  RECEIVE_3_RX_PARITY_ERROR     0x80
#define  RECEIVE_3_RX_OVERRUN_ERROR    0x40
#define  RECEIVE_3_RX_FRAMING_ERROR    0x20
#define  RECEIVE_3_RX_NO_ERROR         0xE0

#define  RECEIVE_3_RX_NO_DATA         0x01

#define  RECEIVE_3_RX_BUF_ERROR           0xF0  // Mask for any Rx that may occur.
#define  RECEIVE_3_RX_BUF_OVERRUN         0x10  // This indicates the software buffer has
                                                           // been over run.
#define  RECEIVE_3_RX_BUF_CMDTERM         0x01  // Command terminator has been received.

// Old defines, will be removed in future release
#define  RX8_PARITY_NONE         0x00
#define  RX8_PARITY_EVEN         0x02
#define  RX8_PARITY_ODD          0x06
#define  RX8_RX_ACTIVE           0x10
#define  RX8_RX_COMPLETE         0x08
#define  RX8_RX_PARITY_ERROR     0x80
#define  RX8_RX_OVERRUN_ERROR    0x40
#define  RX8_RX_FRAMING_ERROR    0x20
#define  RX8_RX_NO_ERROR         0xE0

//-------------------------------------------------
// Register Addresses for RECEIVE_3
//-------------------------------------------------
#pragma ioport  RECEIVE_3_CONTROL_REG:  0x03b              // Control register
BYTE            RECEIVE_3_CONTROL_REG;
#pragma ioport  RECEIVE_3_RX_SHIFT_REG: 0x038              // RX Shift Register register
BYTE            RECEIVE_3_RX_SHIFT_REG;
#pragma ioport  RECEIVE_3_RX_BUFFER_REG:    0x03a              // RX Buffer Register
BYTE            RECEIVE_3_RX_BUFFER_REG;
#pragma ioport  RECEIVE_3_FUNC_REG: 0x138                  // Function register
BYTE            RECEIVE_3_FUNC_REG;
#pragma ioport  RECEIVE_3_INPUT_REG:    0x139              // Input register
BYTE            RECEIVE_3_INPUT_REG;
#pragma ioport  RECEIVE_3_OUTPUT_REG:   0x13a              // Output register
BYTE            RECEIVE_3_OUTPUT_REG;

// end of file RECEIVE_3.h

